"""create_tourists_table

Revision ID: 63ba620c4c90
Revises: a2d374312368
Create Date: 2026-08-07 23:28:43.133878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ba620c4c90'
down_revision: Union[str, Sequence[str], None] = 'a2d374312368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('touriste', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_touriste_email'), 'touriste', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_touriste_email'), table_name='touriste')
    op.drop_column('touriste', 'email')
    # ### end Alembic commands ###
