name: Synchronisation automatique

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Pousser vers le Compte B
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}
          repository: "pixel-dev-26/api_fast_gstock.git"
          branch: "main"
