name: Synchronisation automatique

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Synchronisation vers Compte B
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "andriamiarintsoaKevin/Api_Tolotra"
          source_branch: "main"
          destination_repo: "pixel-dev-26/api_fast_gstock"
          destination_branch: "main"
          github_token: ${{ secrets.SYNC_TOKEN }}
