name: Synchronisation automatique

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pousser vers le Compte B
        env:
          TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git config --global user.name "andriamiarintsoaKevin"
          git config --global user.email "votre-email@example.com"
          git remote add target https://pixel-dev-26:${TOKEN}@github.com/pixel-dev-26/api_fast_gstock.git
          git push -u target main --force
